#!/usr/bin/env node

/**
 * StreetBites Setup Script
 * Run this after cloning to get started quickly
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question) {
  return new Promise(resolve => rl.question(question, resolve));
}

async function setup() {
  console.log('\n🚀 StreetBites Setup\n');
  console.log('This will help you configure your environment variables.\n');

  // Check if .env.local already exists
  if (fs.existsSync('.env.local')) {
    const overwrite = await ask('.env.local already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('\n📦 Step 1: Supabase Configuration');
  console.log('Go to https://supabase.com and create a project (free)');
  console.log('Then go to Settings > API\n');

  const supabaseUrl = await ask('Enter your Supabase Project URL: ');
  const supabaseKey = await ask('Enter your Supabase Anon Key: ');

  console.log('\n🤖 Step 2: Google Gemini AI');
  console.log('Go to https://aistudio.google.com/apikey');
  console.log('Create a new API key (free tier available)\n');

  const geminiKey = await ask('Enter your Gemini API Key: ');

  console.log('\n📍 Step 3: Map Configuration (optional)');
  console.log('Set your default map center location\n');

  const lat = await ask('Default Latitude (press Enter for New York): ') || '40.7128';
  const lng = await ask('Default Longitude (press Enter for -74.0060): ') || '-74.0060';

  // Create .env.local file
  const envContent = `# StreetBites Environment Configuration
# Generated by setup script

# Supabase Configuration
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseKey}

# Google Gemini AI Configuration
VITE_GEMINI_API_KEY=${geminiKey}

# App Configuration
VITE_APP_URL=http://localhost:5173
VITE_MAP_DEFAULT_CENTER_LAT=${lat}
VITE_MAP_DEFAULT_CENTER_LNG=${lng}
VITE_MAP_DEFAULT_ZOOM=13

# GPS Tracking Configuration
VITE_GPS_UPDATE_INTERVAL=30000
VITE_GPS_HIGH_ACCURACY=true

# Feature Flags
VITE_ENABLE_PUSH_NOTIFICATIONS=true
VITE_ENABLE_AI_PREDICTIONS=true
VITE_ENABLE_SOCIAL_FEATURES=true
`;

  fs.writeFileSync('.env.local', envContent);

  console.log('\n✅ Configuration saved to .env.local\n');
  console.log('📋 Next steps:\n');
  console.log('1. Run the database schema:');
  console.log('   - Go to your Supabase project');
  console.log('   - Open SQL Editor');
  console.log('   - Paste content from supabase-schema.sql');
  console.log('   - Click "Run"\n');
  console.log('2. Install dependencies:');
  console.log('   npm install\n');
  console.log('3. Start development server:');
  console.log('   npm run dev\n');
  console.log('🎉 Happy coding!\n');

  rl.close();
}

setup().catch(error => {
  console.error('Setup error:', error);
  rl.close();
  process.exit(1);
});
